name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: WalliCode
          svg_out_path: snake.svg
          
      - name: Push to output branch
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const repo = context.repo
            const snakeContent = fs.readFileSync('snake.svg', 'utf8')
            
            await github.rest.repos.createOrUpdateFileContents({
              owner: repo.owner,
              repo: repo.repo,
              path: 'github-contribution-grid-snake.svg',
              message: 'Update snake animation',
              content: Buffer.from(snakeContent).toString('base64'),
              branch: 'output'
            })
