name: Generate and Deploy Snake Animation

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 16 * * *"  # Executa diariamente às 16:00 UTC

jobs:
  generate-animations:
    name: Generate Animations
    runs-on: ubuntu-latest  # Mudei para ubuntu-latest por compatibilidade
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Snake Animations
        uses: Platane/snk/svg-only@v3.3.0
        with:
          github_user_name: WalliCode
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
            dist/grid-snake-light.svg?palette=github-light

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snake-animations
          path: dist/

  deploy:
    name: Deploy to Pages
    needs: generate-animations
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: snake-animations
          path: dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
