name: Snake Animation Generator

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 16 * * *"  # Runs daily at 16:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: WalliCode
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark
            snake-light.svg?palette=github-light

      - name: Create dist folder
        run: |
          mkdir -p dist
          mv snake.svg dist/
          mv snake-dark.svg dist/
          mv snake-light.svg dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: dist/
          retention-days: 1

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: snake-artifacts
          path: dist/

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
