name: Update Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # A cada 6 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: WalliCode
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Commit and Push
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
